#!/usr/bin/env python3
"""Generate Osaka/Hyogo trucking outreach leads CSV/JSON from curated public sources."""

from __future__ import annotations

import csv
import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent

# Fields written to CSV/JSON. Emails and Instagram handles are only those
# published on official sites or association PDFs — never guessed.
FIELDS = [
    "id",
    "wave",
    "fit",
    "prefecture",
    "city",
    "company",
    "address",
    "tel",
    "fax",
    "email",
    "instagram",
    "website",
    "contact_form",
    "other_sns",
    "representative",
    "employees",
    "trucks",
    "size_note",
    "best_channel",
    "source",
    "notes",
]


def L(**kwargs: str) -> dict[str, str]:
    row = {k: "" for k in FIELDS}
    row.update({k: str(v) for k, v in kwargs.items() if v is not None})
    return row


LEADS: list[dict[str, str]] = [
    # ----- Wave 1: size close to 10 trucks / ~8-15 staff + digital contact -----
    L(
        wave=1, fit="high", prefecture="大阪府", city="門真市",
        company="ITP株式会社",
        address="〒571-0032 大阪府門真市寿町20-27 Edel Buro 501",
        tel="06-6916-7666", fax="06-6916-8879",
        website="https://i-tp.co.jp/",
        contact_form="https://i-tp.co.jp/contact/",
        representative="西山 剛", employees="12", trucks="10",
        size_note="公式会社概要: 従業員12名・保有車両10台（冷凍冷蔵中心）",
        best_channel="form",
        source="https://i-tp.co.jp/company/companyoutline/",
        notes="車庫 門真市桑才新町33-10 TEL 06-4397-7972。冷凍食品配送。規模がターゲットに最も近い。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="大阪市此花区",
        company="有限会社アルディック",
        address="〒554-0052 大阪市此花区常吉2-11-47",
        tel="06-6468-7772", fax="06-6464-5108",
        email="ochi@aldic.co.jp",
        website="https://aldic.co.jp/",
        contact_form="https://aldic.co.jp/%e3%81%8a%e5%95%8f%e3%81%84%e5%90%88%e3%82%8f%e3%81%9b/",
        representative="越智 隆之", employees="14", trucks="13",
        size_note="公式: 従業員14名。車両=トレーラー2+大型1+4t×8+3t×1+1t×1（フォーク除く）",
        best_channel="email",
        source="https://aldic.co.jp/%e4%bc%9a%e7%a4%be%e6%a6%82%e8%a6%81/",
        notes="ハローワーク求人票にも ochi@aldic.co.jp が担当メールとして掲載。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="東大阪市",
        company="宝伸有限会社",
        address="大阪府東大阪市本庄1-13-14",
        tel="072-968-6102", fax="072-968-6103",
        email="info@hoshin-cargo.com",
        instagram="https://www.instagram.com/hoshin1717/",
        website="https://www.hoshin-cargo.com/",
        representative="三宅 秀樹", employees="14", trucks="12",
        size_note="公式会社概要: 従業員14人・車両台数12台",
        best_channel="email",
        source="https://www.hoshin-cargo.com/company/",
        notes="Instagram @hoshin1717。メールとDMの両方可。2t〜トレーラーまで保有。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="枚方市",
        company="大阪ライン有限会社",
        address="〒573-0122 大阪府枚方市津田東町1-26-5",
        tel="072-808-5060", fax="072-808-5061",
        website="https://osakaline.co.jp/",
        representative="一宮 將人", employees="14", trucks="15",
        size_note="公式: 従業員14名。13t平1 / 4tW5 / 4t平1 / 2t平8 = 15台",
        best_channel="tel",
        source="https://osakaline.co.jp/%e4%bc%9a%e7%a4%be%e6%a6%82%e8%a6%81/",
        notes="東大阪倉庫 TEL 06-6753-7101。大正支部リンクにも社名あり。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="大阪市大正区",
        company="清家運送有限会社",
        address="〒551-0021 大阪市大正区南恩加島5-3-5",
        tel="06-6551-4343", fax="06-6551-2207",
        website="https://www.seikeunsou.co.jp/",
        representative="清家 学", employees="18", trucks="15",
        size_note="公式: 従業員18名。トレーラー3+4tユニック2+3tユニック5+2tユニック1+PG4",
        best_channel="tel",
        source="https://www.seikeunsou.co.jp/company",
        notes="大阪府ト協会西支部会員。鋼材・エレベーター部材。メール未掲載。",
    ),
    L(
        wave=1, fit="high", prefecture="兵庫県", city="神戸市北区",
        company="有限会社スミレ運輸",
        address="〒651-1351 神戸市北区八多町中1170",
        tel="078-950-2009", fax="078-950-2323",
        website="http://www.kobesumirenet.com/",
        contact_form="http://www.kobesumirenet.com/",
        representative="山脇 利男", employees="14", trucks="12",
        size_note="公式: 大型冷凍冷蔵車11台+大型トレーラー1台。被保険者約14名",
        best_channel="tel",
        source="http://www.kobesumirenet.com/category/1504598.html",
        notes="担当: 山脇。冷凍冷蔵地場。問い合わせフォームあり。",
    ),
    L(
        wave=1, fit="high", prefecture="兵庫県", city="姫路市",
        company="有限会社姫路キャリー",
        address="〒671-1101 姫路市広畑区東夢前台4-96-2",
        tel="079-239-2554", fax="079-239-5585",
        email="info@himeji-carry.com",
        website="http://himeji-carry.com/",
        employees="5",
        size_note="公開企業情報: 被保険者5名。軽〜4tの小口・急送中心",
        best_channel="email",
        source="http://himeji-carry.com/toiawase.html",
        notes="24時間受付と明記。車両10台規模より小さいが、トラックキャビン清掃の導入はしやすい。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="八尾市",
        company="河本運送有限会社",
        address="〒581-0042 大阪府八尾市南木の本5-5",
        tel="072-922-2727",
        instagram="https://www.instagram.com/kawamoto_unsou/",
        website="https://www.kawamoto-unsou-yao.com/",
        other_sns="X @kawamoto_unsou",
        employees="23",
        size_note="被保険者約23名。食品配送。公式がSNSのDM問い合わせを案内",
        best_channel="instagram",
        source="https://www.kawamoto-unsou-yao.com/",
        notes="電話は公式・電話帳で0729-22-2727表記あり。DM歓迎と明記。規模はやや上。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="大阪市住吉区",
        company="有限会社エムシイエス",
        address="大阪市住吉区南住吉1-6-3 MCSビル2F",
        tel="06-6691-4471", fax="06-6691-4470",
        instagram="https://www.instagram.com/mcs_634/",
        website="https://mcs.jpn.com/",
        size_note="重量物・クレーン。公式Instagram @mcs_634",
        best_channel="instagram",
        source="https://mcs.jpn.com/",
        notes="車庫: 堺市美原区大保232-1。特殊車両中心。キャビン汚れが出やすい車種。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="東大阪市",
        company="株式会社奥辰運輸",
        address="〒577-0066 大阪府東大阪市高井田本通7-1-23",
        tel="06-6781-7007", fax="06-6781-7023",
        website="https://okutatsu-unyu.com/",
        contact_form="https://okutatsu-unyu.com/about",
        representative="井岡 晋", employees="22-35", trucks="10+",
        size_note="公式: 大型ウイング10台。ハローワークは従業員22〜35名と幅あり",
        best_channel="form",
        source="https://okutatsu-unyu.com/about",
        notes="サイトに『営業電話お断り』。メールフォームのみ。",
    ),
    L(
        wave=1, fit="medium", prefecture="大阪府", city="大阪市大正区",
        company="筑前運輸株式会社",
        address="〒551-0002 大阪市大正区三軒家東4-12-9",
        tel="06-6551-3030", fax="06-6551-3034",
        website="https://www.chikuzen-unyu.com/",
        representative="岡野 信正", employees="26", trucks="20",
        size_note="公式: トレーラー11+10t×7+6t×2、従業員26人",
        best_channel="tel",
        source="https://www.chikuzen-unyu.com/",
        notes="大正支部。鋼材。ターゲットよりやや大きいが地場の中堅。",
    ),
    L(
        wave=1, fit="medium", prefecture="大阪府", city="茨木市",
        company="有限会社ミナミ（茨木）",
        address="〒567-0815 大阪府茨木市竹橋町1-21-2",
        tel="072-628-9702", fax="072-628-9703",
        website="https://minami-m3.com/",
        contact_form="https://minami-m3.com/pages/5/",
        representative="佐和 崇", employees="20", trucks="20",
        size_note="公式: 従業員20名。4t系ウイング/冷凍等 2+4+1+7+2+3+1=20台",
        best_channel="form",
        source="https://minami-m3.com/pages/17/",
        notes="西堀江の（有）ミナミ（南港）とは別法人。雑貨・医薬品。",
    ),
    L(
        wave=1, fit="high", prefecture="兵庫県", city="姫路市",
        company="株式会社フィールドジャパン",
        address="〒670-0955 姫路市安田4-35 カトウビル4F",
        tel="079-287-8444",
        representative="", employees="9",
        size_note="ハローワーク: 企業全体9人。コンビニ等食品ルート配送",
        best_channel="tel",
        source="https://helloworkplus.com/job/28050-17217361/",
        notes="2017年創業。HPなし。電話は求人票掲載値のため発信前に再確認。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="大阪市浪速区",
        company="柴崎運送株式会社",
        address="〒556-0022 大阪市浪速区桜川4-5-17",
        tel="06-6561-0293",
        employees="5",
        size_note="ハローワーク: 企業全体5人。溶接材料商社専属",
        best_channel="tel",
        source="https://ricareer.jp/hellowork/27030-19448661/",
        notes="超小型。キャビン清掃の導入判断が速い層。",
    ),
    L(
        wave=1, fit="high", prefecture="大阪府", city="大阪市北区",
        company="袖川運送店",
        address="〒530-0043 大阪市北区天満3-5-16",
        tel="06-6352-0734",
        employees="14",
        size_note="ハローワーク: 企業全体14人（就業13人）。1953年創業",
        best_channel="tel",
        source="https://www.mapion.co.jp/phonebook/M21006/27127/22733109648/",
        notes="車庫は西淀川区竹島側の求人あり。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="神戸市兵庫区",
        company="株式会社福住",
        address="〒652-0813 神戸市兵庫区兵庫町1-4-26",
        tel="0120-11-4021",
        email="info@fukuzumi-m.com",
        website="https://www.fukuzumi-m.com/",
        representative="福住 正則",
        size_note="兵ト協引越部会長。地域密着の引越業者（規模は公式未詳）",
        best_channel="email",
        source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf",
        notes="協会PDF掲載メール。引越車両のキャビン需要。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="神戸市兵庫区",
        company="平戸梱包運送株式会社（ヒカリ引越センター）",
        address="〒652-0882 神戸市兵庫区芦原通4-2-27",
        tel="078-651-6950",
        email="info@8144.co.jp",
        website="http://www.8144.co.jp/",
        representative="平戸 伸和",
        size_note="兵ト協引越部会。創業70年超の地域引越",
        best_channel="email",
        source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf",
        notes="協会PDF掲載メール。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="神戸市東灘区",
        company="松本運送株式会社（ホームハンズ）",
        address="〒658-0044 神戸市東灘区御影塚町1-10-7",
        tel="078-843-0450",
        email="info@homehands.co.jp",
        website="https://www.homehands.co.jp/",
        representative="松本 賢吾",
        size_note="兵ト協引越部会。阪神間の引越",
        best_channel="email",
        source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf",
        notes="協会PDF掲載メール。ブランド名ホームハンズ / はこびー。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="神戸市東灘区",
        company="株式会社ブレックス",
        address="〒658-0012 神戸市東灘区本庄町2-4-12",
        tel="0120-06-1954",
        email="info@blex.co.jp",
        website="https://www.blex.co.jp/",
        representative="大久保 尚男",
        size_note="兵ト協引越部会。Gマーク・引越安心マーク",
        best_channel="email",
        source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf",
        notes="協会PDF掲載メール。YouTubeも運用。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="尼崎市",
        company="堀部運送株式会社",
        address="〒661-0012 尼崎市南塚口町2-12-21",
        tel="0120-88-1290",
        email="mitsumori@horibe-unso.co.jp",
        website="http://www.horibe-unso.co.jp/",
        representative="外薗 英広",
        size_note="兵ト協引越部会。一般貨物も。新車2t納車の告知あり",
        best_channel="email",
        source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf",
        notes="協会PDFの見積メール。代表TEL 06-6429-1292。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="神戸市西区",
        company="株式会社シティ・サービス",
        address="〒651-2111 神戸市西区池上1-14-2",
        tel="0120-02-0011",
        email="hikkoshi.0011@city020011.jp",
        website="https://www.city020011.jp/",
        representative="小原 美子",
        size_note="兵ト協引越部会",
        best_channel="email",
        source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf",
        notes="協会PDF掲載メール。サイト移転の案内あり。送付前にURL確認。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="神戸市兵庫区",
        company="兵庫貨物運輸作業株式会社",
        address="〒652-0882 神戸市兵庫区芦原通2-2-24",
        tel="0120-19-5444",
        email="hku@chive.ocn.ne.jp",
        representative="廣瀬 義一",
        size_note="兵ト協引越部会（ヤマサ引越）",
        best_channel="email",
        source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf",
        notes="協会PDF掲載のOCNメール。",
    ),
    L(
        wave=1, fit="medium", prefecture="兵庫県", city="伊丹市",
        company="和晃運輸株式会社",
        address="〒664-0888 伊丹市昆陽南5-1-43",
        tel="072-771-2121", fax="072-771-2500",
        email="hikkoshi@wako-unyu.co.jp",
        website="https://www.wako-unyu.co.jp/",
        representative="佐藤 寿彦", employees="55", trucks="47",
        size_note="公式: 従業員55名・車両47台。ターゲットより大きい",
        best_channel="email",
        source="https://www.wako-unyu.co.jp/company/",
        notes="info@wako-unyu.co.jp も公式掲載。引越部門宛てが無難。中堅として参考掲載。",
    ),
    L(
        wave=1, fit="high", prefecture="兵庫県", city="神戸市西区",
        company="有限会社西村運送店",
        address="神戸市西区伊川谷町小寺字吉末126（登記: 須磨区白川台5-7-3）",
        employees="10",
        representative="勢登 健司",
        size_note="ハローワーク: 企業全体10人。アスファルト合材・残土",
        best_channel="tel",
        source="https://hataraku-search.com/companies/2820-615319-9",
        notes="公開固定電話が見つからず。兵ト協ダンプ部会名簿掲載。タウンページで番号確認してから架電。",
    ),
    # ----- Wave 2: Osaka Truck Association West branch — yugen / local -----
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市平野区", company="有限会社丸将配送", address="〒547-0014 大阪市平野区長吉川辺3-19-25", tel="06-6700-1937", fax="06-6700-1938", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。規模未確認（有限会社）。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="蓮井運輸倉庫有限会社", address="〒550-0025 大阪市西区九条南2-24-12", tel="06-6581-0061", fax="06-6581-0065", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="有限会社松岡組", address="〒550-0023 大阪市西区千代崎1-2-41", tel="06-6626-9263", fax="06-6626-9264", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。神戸の土木・松岡組とは別。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="堺市美原区", company="有限会社ジェイウェーブ", address="〒587-0012 堺市美原区多治井156-1", tel="072-363-7700", fax="072-363-4400", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="有限会社タイホウ", address="〒551-0021 大阪市大正区南恩加島5-4-1", tel="06-6551-3123", fax="06-6551-3124", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="有限会社サンミ", address="〒550-0021 大阪市西区川口4-33", tel="06-6581-3637", fax="06-6581-3687", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。産廃の株式会社三美とは別。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="茨木市", company="有限会社成和配送", address="〒567-0015 茨木市西太田町6-20", tel="072-626-6628", fax="072-626-6628", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。TEL=FAX。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="正和運送有限会社", address="〒550-0015 大阪市西区南堀江1-27-9", tel="06-6531-0515", fax="06-6536-1080", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="有限会社領家運送", address="〒551-0021 大阪市大正区南恩加島5-8-79", tel="06-6554-2021", fax="06-6551-4148", website="http://ryoke-transport.co.jp/wordpress/", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="重量部会にも掲載。サイトはWordPress初期状態。電話優先。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="有限会社大阪西配送センター", address="〒551-0013 大阪市大正区小林西1-14-8", tel="06-6554-0111", fax="06-6554-0013", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部会員。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="有限会社ミナミ（西区新町）", address="〒550-0013 大阪市西区新町2-3-8 DOビル新町201", tel="06-4394-7801", fax="06-4394-7802", website="https://minami-exp.com/", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="輸出入。車両26台の記載あり（2018）。茨木の有限会社ミナミとは別。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="小河運輸株式会社", address="〒550-0025 大阪市西区九条南4-16-6", tel="06-6582-2785", fax="06-6582-2786", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。地場運送の社名。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="九條運送株式会社", address="〒550-0025 大阪市西区九条南2-20-12", tel="06-6582-2410", fax="06-6582-1730", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="大阪西運送株式会社", address="〒550-0025 大阪市西区九条南1-2-20", tel="06-6581-6651", fax="06-6581-7675", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="西邦運送株式会社", address="〒550-0025 大阪市西区九条南2-29-12", tel="06-6584-5658", fax="06-6584-5315", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="宮瀧運輸株式会社", address="〒550-0022 大阪市西区本田4-7-20", tel="06-6582-2064", fax="06-6582-1053", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。尼崎営業所あり。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="海協運送株式会社", address="〒550-0023 大阪市西区千代崎2-2-4", tel="06-6582-2905", fax="06-6581-2505", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="日吉運送株式会社", address="〒550-0015 大阪市西区南堀江4-12-20", tel="06-6531-8118", fax="06-6531-8280", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="松原運輸株式会社", address="〒550-0015 大阪市西区南堀江4-2-10", tel="06-6541-0703", fax="06-6541-0704", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="丸洲運輸株式会社", address="〒550-0015 大阪市西区南堀江4-32-18", tel="06-6531-8551", fax="06-6531-8552", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="和光運輸株式会社", address="〒550-0015 大阪市西区南堀江4-23-5", tel="06-6532-2112", fax="06-6532-2139", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="若狭組運送株式会社", address="〒550-0015 大阪市西区南堀江4-2-17", tel="06-6531-5400", fax="06-6531-5296", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西成区", company="新町運輸株式会社", address="〒557-0022 大阪市西成区中開3-1-19", tel="06-6556-6741", fax="06-6556-6742", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="株式会社中田運輸", address="〒551-0021 大阪市大正区南恩加島6-17-4", tel="06-6555-7775", fax="06-6555-7767", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市住之江区", company="御崎運輸株式会社", address="〒559-0013 大阪市住之江区御崎1-2-28", tel="06-6684-6133", fax="06-6684-6134", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="大機運輸株式会社", address="〒551-0002 大阪市大正区三軒家東2-1-8", tel="06-6552-4573", fax="06-6552-0530", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市此花区", company="田村運送株式会社", address="〒554-0052 大阪市此花区常吉2-5-14", tel="06-6462-9163", fax="06-6461-0176", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市住吉区", company="上義運輸株式会社", address="〒558-0055 大阪市住吉区万代5-17-32", tel="06-6673-6319", fax="06-6673-6319", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。TEL=FAX。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西区", company="木村運輸株式会社", address="〒550-0024 大阪市西区境川2-2-32", tel="06-6584-2501", fax="06-6584-2505", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="守口市", company="木下運送株式会社", address="〒570-0013 守口市東町2-10-18", tel="06-6902-5767", fax="06-6903-7445", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部（所在は東北支部エリア）。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="門真市", company="白瀬運輸株式会社", address="〒571-0017 門真市四宮3-2-19", tel="072-881-5235", fax="072-881-6554", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部名簿。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="門真市", company="広栄配送サービス株式会社", address="〒571-0015 門真市三ツ島3-5-34", tel="072-803-6575", fax="072-803-6576", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部名簿。配送特化。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="寝屋川市", company="東和運送株式会社", address="〒572-0814 寝屋川市堀溝2-10-1 ココプラザ101", tel="072-823-9000", fax="072-823-9001", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。コールドエクスプレスと同居記載。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="枚方市", company="東洋運送株式会社", address="〒573-0065 枚方市出口1-427-1", tel="072-846-3431", fax="072-846-3446", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部名簿。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大東市", company="摂友株式会社", address="〒574-0056 大東市新田中町1-20", tel="072-873-6255", fax="072-873-6287", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部名簿。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="摂津市", company="東海運送株式会社", address="〒566-0052 摂津市鳥飼本町3-3-31", tel="072-654-0654", fax="072-654-0654", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。TEL=FAX。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="摂津市", company="昌南運輸株式会社", address="〒566-0062 摂津市鳥飼上3-15-27", tel="072-654-7344", fax="072-653-0731", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="茨木市", company="信喜運輸株式会社", address="〒567-0053 茨木市豊原町4-40", tel="072-643-5683", fax="072-643-9411", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="茨木市", company="栄和運輸株式会社", address="〒567-0005 茨木市五日市1-8-8", tel="072-623-1924", fax="072-623-1927", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="東大阪市", company="株式会社平野運輸", address="〒578-0921 東大阪市水走1-10-7", tel="072-968-0015", fax="072-968-0019", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部名簿。宝伸と同エリア。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="東大阪市", company="渡部産業株式会社", address="〒578-0904 東大阪市吉原2-8-4", tel="072-967-2158", fax="072-967-2159", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部名簿。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市平野区", company="大真運輸株式会社", address="〒547-0022 大阪市平野区瓜破東2-1-43", tel="06-6707-3715", fax="06-6708-4548", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="堺市堺区", company="株式会社マツバヤシ", address="〒590-0814 堺市堺区石津町3-14-15", tel="072-243-3237", fax="072-243-3236", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="松原市", company="大栄運輸産業株式会社", address="〒580-0013 松原市丹南1-482-6", tel="072-335-1321", fax="072-335-1506", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市住之江区", company="八木運送株式会社", address="〒559-0022 大阪市住之江区緑木1-4-108", tel="06-6681-0103", fax="06-6681-0106", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。ドラEVERでは大型の記載もあるため規模要確認。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市住吉区", company="株式会社なにわライン", address="〒558-0041 大阪市住吉区南住吉1-2-3", tel="06-6699-5053", fax="06-6699-5648", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西成区", company="樽芳運輸株式会社", address="〒557-0062 大阪市西成区津守3-6-10", tel="06-6653-6101", fax="06-6653-6688", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市西成区", company="貝塚運送株式会社", address="〒557-0063 大阪市西成区南津守5-6-22", tel="06-6657-3562", fax="06-6657-3574", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。社名は貝塚だが所在は西成。"),
    L(wave=2, fit="unknown", prefecture="大阪府", city="大阪市港区", company="大阪小山武運送株式会社", address="〒552-0013 大阪市港区福崎2-4-17", tel="06-6574-8445", fax="06-6575-0566", best_channel="tel", source="http://nishi.truck.or.jp/meibo.html", notes="西支部。"),
    # ----- Wave 3: Hyogo dump assoc + local yugen directories -----
    L(wave=3, fit="unknown", prefecture="兵庫県", city="神戸市兵庫区", company="相田運輸株式会社", address="神戸市兵庫区築地町1-26", tel="078-651-0988", representative="相田 眞宏", website="https://www.kensetumap.com/company/379864/profile.php", best_channel="tel", source="https://www.hyotokyo.or.jp/member-public/15-11-dump.html", notes="兵ト協ダンプ部会。土木も。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="神戸市中央区", company="株式会社松原組運送", address="神戸市中央区南本町通", tel="078-221-7745", website="http://matsubaragumiunsou.co.jp/", best_channel="tel", source="https://www.hyotokyo.or.jp/member-public/15-11-dump.html", notes="ダンプ部会。Gマーク。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="株式会社髙津組", address="尼崎市西昆陽3-4-5", tel="06-6433-8600", best_channel="tel", source="https://www.hyotokyo.or.jp/member-public/15-11-dump.html", notes="ダンプ部会。運送ノート掲載TEL。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="上津運輸株式会社", address="姫路市広畑区富士町1", tel="079-236-1405", best_channel="tel", source="https://www.hyotokyo.or.jp/member-public/15-11-dump.html", notes="ダンプ部会。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="小谷運送株式会社", address="〒670-0851 姫路市京口町109", tel="079-224-8330", website="https://kotaniunsou.co.jp/", best_channel="tel", source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf", notes="引越部会・ハトのマーク姫路北。山田町南山田の別番号079-263-2537あり。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="信栄運輸株式会社", address="〒671-0254 姫路市花田町勅旨426-8", tel="079-253-5820", representative="福永 吉秀", best_channel="tel", source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf", notes="引越部会。運送ノートは079-253-5820。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="株式会社浜田運送", address="〒672-8023 姫路市白浜町乙221-5", tel="079-245-5221", representative="濵田 長伸", best_channel="tel", source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf", notes="引越部会。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="神戸市灘区", company="有限会社廣垣急送", address="〒657-0844 神戸市灘区都通5-4-3", tel="078-871-1954", representative="廣垣 和子", website="http://hato-kansai.or.jp", best_channel="tel", source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf", notes="ハトのマーク神戸東。女性経営。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="神戸市須磨区", company="武貞物流株式会社", address="〒654-0121 神戸市須磨区妙法寺字東谷843-1", tel="078-741-0680", representative="武貞 明彦", best_channel="tel", source="http://www.hyotokyo.or.jp/hikkoshiguidebook/pdf/hikkosibukai-meibo.pdf", notes="引越部会。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="有限会社岡本運輸", address="姫路市大津区真砂町38-33", tel="079-237-0739", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="有限会社尾上運送", address="姫路市飾磨区構3-406", tel="079-234-3111", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="有限会社木下運送店", address="姫路市京口町24", tel="079-282-3553", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="有限会社蔵元商運", address="姫路市別所町別所5-79", tel="079-253-3900", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="坂口運送有限会社", address="姫路市林田町新町1101", tel="079-261-3964", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="神興運輸有限会社", address="姫路市大津区勘兵衛町2-260-4", tel="079-239-5022", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="有限会社竹弘運輸", address="姫路市花田町勅旨47-3", tel="079-253-5815", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="有限会社辰本運輸", address="姫路市三条町1-51", tel="079-282-4423", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="姫路市", company="有限会社グレイスキャリー", address="姫路市書写1732-13", tel="079-266-1100", best_channel="tel", source="https://transport-company.jp/information/hyogo/himeji/", notes="電話帳。小口配送系の社名。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社秋山運送", address="尼崎市尾浜町2-13-16", tel="06-6422-7588", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社ウエストライナー", address="尼崎市大庄川田町44", tel="06-6415-9807", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="内田運輸有限会社", address="尼崎市猪名寺1-21-35", tel="06-6491-8059", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社門脇運輸", address="尼崎市栗山町1-22-12", tel="06-6427-1555", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="杉村運送有限会社", address="尼崎市久々知1-11-5", tel="06-6493-2365", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社誠和運輸", address="尼崎市食満3-8-1-207", tel="06-6492-7281", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="丸二配送有限会社", address="尼崎市猪名寺1-19-18", tel="06-6491-0505", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。配送特化。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社三濃運送店", address="尼崎市次屋3-3-23", tel="06-6499-5270", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社森運輸", address="尼崎市若王寺3-23-43", tel="06-6491-0248", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="吉井運送有限会社", address="尼崎市末広町1-3-17", tel="06-6413-2003", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="山二陸運有限会社", address="尼崎市西立花町3-10-33", tel="06-6418-5300", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社シンコー運送サービス", address="尼崎市浜田町2-69", tel="06-6413-9901", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳。有限会社。"),
    L(wave=3, fit="unknown", prefecture="兵庫県", city="尼崎市", company="有限会社オーケーコーポレーション", address="尼崎市常松2-17-4", tel="06-6437-7200", employees="13", size_note="企業DB上 被保険者約13名（冷凍冷蔵）", best_channel="tel", source="https://transport-company.jp/information/hyogo/amagasaki/", notes="電話帳表記はＯＫコーポレーション。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="今井運送株式会社", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク掲載。番号は支部TEL 06-6554-3431経由かタウンページで確認。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="中村運送株式会社", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="有限会社岡田商会", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。有限会社。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="有限会社栗本商店", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。有限会社。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="株式会社寿運送", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="坂本梱包有限会社", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。梱包+運送。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="有限会社三愛", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="株式会社二村運送店", address="大阪市大正区", tel="06-6409-0031", notes="大正支部。尼崎営業所TELを運送ノートで確認。本社番号は要確認。", best_channel="tel", source="http://taisho.truck.or.jp/link.html"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="石丸運輸株式会社", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。"),
    L(wave=3, fit="unknown", prefecture="大阪府", city="大阪市大正区", company="泉尾運送株式会社", address="大阪市大正区", best_channel="tel", source="http://taisho.truck.or.jp/link.html", notes="大正支部リンク。"),
]


def main() -> None:
    for i, row in enumerate(LEADS, start=1):
        row["id"] = f"OKH-{i:03d}"
        row["wave"] = str(row["wave"])

    csv_path = OUT_DIR / "leads.csv"
    json_path = OUT_DIR / "leads.json"

    with csv_path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(LEADS)

    json_path.write_text(
        json.dumps(LEADS, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    n = len(LEADS)
    osaka = sum(1 for r in LEADS if r["prefecture"] == "大阪府")
    hyogo = sum(1 for r in LEADS if r["prefecture"] == "兵庫県")
    w1 = sum(1 for r in LEADS if r["wave"] == "1")
    email_n = sum(1 for r in LEADS if r["email"])
    ig_n = sum(1 for r in LEADS if r["instagram"])
    print(f"Wrote {n} leads ({osaka} Osaka, {hyogo} Hyogo). wave1={w1} email={email_n} instagram={ig_n}")
    print(f"CSV: {csv_path}")
    print(f"JSON: {json_path}")


if __name__ == "__main__":
    main()
